name: Reuseable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deploy step
        value: ${{ jobs.deploy.outputs.outcome}}
    # secrets:
    #   some_secret:
    #     description: A secret to use in the deploy step
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls -R
      - name: Output Information
        run: echo "Deploying and uploading"
      - name: Set Result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT